# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609b0d0a33aa363b53b6c2e87bf6e6b525d7951b768a523faef453f8150e88788612c6110ce450f1138f528f36fc1e6079cf83c8cafb0c620e73d70fd4f8f69f

test:
  secret_key_base: 4371b7020d7979c50ec2d633f609ade2b2688df0775c9b340417a5f5fd959d35289363fb1325b686a7e018c62aa3a419ed5a1ca66a375f402f486cf9aebec63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
